language: android 
android: 
    components: 
        - platform-tools
        - tools
        - build-tools-21.1.1
        - android-21
        - extra
        - sys-img-armeabi-v7a-android-21
before_script:
    - chmod +x gradlew

after_success:
    - echo "Done!" 

notifications:
  email: false
